# Generated by Django 5.1 on 2024-09-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('carbohydrates_total_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cholesterol_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_saturated_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_total_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('potassium_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodium_mg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugar_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
